MisPerris/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mascota/', include('apps.mascota.urls',namespace='mascota')),
    path('contacto/', include('apps.contacto.urls',namespace='contacto')),
    url(r'', include('apps.mascota.urls')),    
]

apps/contacto/urls.py
from django.urls import path,include
from apps.contacto.views import index_contacto,contacto_view, contacto_list

app_name="apps"
urlpatterns = [
	path('nuevo', index_contacto,name='contacto'),
	path('nuevo/', contacto_view,name='nuevocontacto'),
	path('listar/',contacto_list, name='contacto_listar'),
]

apps/mascota/urls.py
from django.urls import path,include
from apps.mascota.views import index, mascota_view,mascota_list
from django.conf.urls import url
app_name="apps"

urlpatterns = [
    url(r'^$', index,name='index'),
    path('nuevo/', mascota_view, name='mascota_crear'),
    path('listar/',mascota_list, name='mascota_listar'),

]

apps/contacto/models.py
from django.db import models

# Create your models here.

class Contacto(models.Model):
	rut = models.CharField(max_length=12)
	com_name = models.CharField(max_length=50)
	email = models.CharField(max_length=50)
	phone = models.CharField(max_length=13)
	reg = models.CharField(max_length=30)
	city = models.CharField(max_length=30)
    

apps/mascota/models.py
from django.db import models

# Create your models here.

class Mascota(models.Model):
	nombre = models.CharField(max_length=50)
	raza = models.CharField(max_length=30)
	descripcion = models.CharField(max_length=100)
	estado = models.CharField(max_length=11)

apps/contacto/forms.py
from django import forms
from apps.contacto.models import Contacto

class ContactoForm(forms.ModelForm):

	class Meta:
		model = Contacto

		fields = [
			'rut',
			'com_name',
			'email',
			'phone',
			'reg',
			'city',

		]

		labels = {
			'rut': 'Rut',
			'com_name': 'Nombre de mascota',
			'email': 'Email', 
			'phone': 'Telefono',
			'reg': 'Region',
			'city': 'Ciudad',
		}

		widgets = {
			'rut': forms.TextInput(attrs={'class':'form-control'}),
			'com_name': forms.TextInput(attrs={'class':'form-control'}),
			'email': forms.TextInput(attrs={'class':'form-control'}),
			'phone': forms.TextInput(attrs={'class':'form-control'}),
			'reg': forms.TextInput(attrs={'class':'form-control'}),
			'city': forms.TextInput(attrs={'class':'form-control'}),
		}

apps/mascota/forms.py
from django import forms

from apps.mascota.models import Mascota

class MascotaForm(forms.ModelForm):

	class Meta:
		model = Mascota

		fields = [
			'nombre',
			'raza',
			'descripcion',
			'estado',
		]
		labels = {
			'nombre': 'Nombre',
			'raza': 'Raza Estimada',
			'descripcion': 'Descripcion',
			'estado': 'Estado',
		}
		widgets = {
			'nombre': forms.TextInput(attrs={'class':'form-control'}),
			'raza': forms.TextInput(attrs={'class':'form-control'}),
			'descripcion': forms.TextInput(attrs={'class':'form-control'}),
			'estado': forms.TextInput(attrs={'class':'form-control'}),
		}

apps/contacto/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from apps.contacto.forms import ContactoForm
from apps.contacto.models import Contacto
# Create your views here.
def index_contacto(request):
	return render("contacto/contacto_form.html")

def contacto_view(request):
	if request.method =='POST':
		form = ContactoForm(request.POST)
		if form.is_valid():
			form.save()
		return redirect('contacto/contacto_form.html')
	else:
		form = ContactoForm()

	return render(request, 'contacto/contacto_form.html',{'form':form})

def contacto_list(request):
	contacto = Contacto.objects.all()
	contexto = {'contacto':contacto}
	return render(request, 'contacto/contacto_list.html',contexto)

apps/mascota/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from apps.mascota.forms import MascotaForm
from apps.mascota.models import Mascota
# Create your views here.

def index(request):
	return render(request, 'base/base.html',{})

def mascota_view(request):
	if request.method =='POST':
		form = MascotaForm(request.POST)
		if form.is_valid():
			form.save()
		return redirect('mascota:index')
	else:
		form = MascotaForm()

	return render(request, 'mascota/mascota_form.html',{'form':form})

def mascota_list(request):
	mascota = Mascota.objects.all()
	contexto = {'mascotas':mascota}
	return render(request, 'mascota/mascota_list.html',contexto)

MisPerris/templates/base/base.html
<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="UTF-8">
	<title>{% block title %} Mis Perris{% endblock %}</title>
</head>
<body>
	{% block header %}
	<h4>MIS PERRITOS</H4>
	{% endblock %}

	{% block content % }
	<h5>Este es el contenido del archivo basep</h5>
	{% endblock %}
</body>
</html>

MisPerris/templates/mascota/index.html
{% extends 'base/base.html' %}

templates/base/base.html
{% load staticfiles %}
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width-device=width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie-edge">
    <title>Mascotas</title> 
    <link rel="stylesheet" type="text/css" href="{% static 'css/estilos.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/bootstrap-theme.css' %}" type="text/css">
</head>
<body>
        <div class="container-fluid">
                <div class="row header">
                    <div class="navbar-header">
                        <a class="navbar-brand" href="index.html"><img src="{% static 'img/logo.png' %}" alt="logo"></a> </div>
                    <nav class="nav navbar-right header heads">
                        <ul class="active">
                            <li><a href="{% url 'mascota:index' %}">Inicio</a></li>
                            <li><a href="{% url 'mascota:mascota_crear' %}">Mascota</a></li>
                            <li><a href="{% url 'contacto:nuevocontacto' %}">Contacto</a></li>
                            <li><a href="{% url 'mascota:mascota_listar' %}">Rescatados</a></li>

                            <li><a href="{% url 'contacto:contacto_listar' %}">Lista de Contactos</a></li>
                        </ul>
                    </nav>
                </div>
                <div id="myCarousel" class="carousel slide row" data-ride="carousel">
                        <!-- Indicators -->
                        <ol class="carousel-indicators">
                          <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                          <li data-target="#myCarousel" data-slide-to="1"></li>
                          <li data-target="#myCarousel" data-slide-to="2"></li>
                          <li data-target="#myCarousel" data-slide-to="3"></li>
                        </ol>
                      
                        <!-- Wrapper for slides -->
                        <div class="carousel-inner">
                          <div class="item active">
                            <img src="{% static 'img/perro1.jpg' %}" alt="Perro1" height=1500 width=1200>
                            <div class="carousel-caption">
                              <h3>Los Inseparables</h3>
                              <p>Jaime, Tomy y Carlangas han traído la felicidad a nuestra casa.</p>
                            </div>
                          </div>
                      
                          <div class="item">
                            <img src="{% static 'img/perro2.jpg' %}" alt="Perro2" height=1500 width=1200>
                            <div class="carousel-caption">
                              <h3>Chuck</h3>
                              <p>Con Chuck encontré el compañero ideal para mis tardes de ejercicios.</p><br><p>Muchas gracias Mis Perris!</p>
                            </div>
                          </div>
                      
                          <div class="item">
                            <img src="{% static 'img/perro3.jpg' %}" alt="Perro3" height=1500 width=1200>
                            <div class="carousel-caption">
                              <h3>Cholito</h3>
                              <p>Aunque esté viejito le sobra energía y amor</p>
                            </div>
                          </div>
    
                          <div class="item">
                                <img src="{% static 'img/perro4.jpg' %}" alt="Perro4" height=1500 width=1200>
                                <div class="carousel-caption">
                                  <h3>Sebastián</h3>
                                  <p>Un poco travieso, pero lo amamos</p>
                                </div>
                              </div>
                        </div>
                      
                        <!-- Left and right controls -->
                        <a class="left carousel-control" href="#myCarousel" data-slide="prev">
                          <span class="glyphicon glyphicon-chevron-left"></span>
                          <span class="sr-only">Previous</span>
                        </a>
                        <a class="right carousel-control" href="#myCarousel" data-slide="next">
                          <span class="glyphicon glyphicon-chevron-right"></span>
                          <span class="sr-only">Next</span>
                        </a>
                      </div>
                <!--<div class="row perro">
                    <section class="col-sm-12 text-center" >
                       <img src="img/perro.png" alt="Perrito" height="400" width="600" id="imagen">
                    </section>
                </div>-->
                <div class="row info justify-content-between">
                        <div class="col-sm-12 col-md-4 col-lg-4 col-xl-4 text-center"><p>+56998735431</p></div>
                        <div class="col-sm-12 col-md-4 col-lg-4 col-xl-4 text-center"><p>Rescate y adopción de perros callejeros</p></div>
                        <div class="col-sm-12 col-md-4 col-lg-4 col-xl-4 text-center">
                            <a href="https://wwww.facebook.com" title="Facebook"><img src="{% static 'img/fblogo.png' %}" alt="Facebook"  width="20px" height="20px"></a>
                            <a href="https://plus.google.com"><img src="{% static 'img/googleplus.png'%}" alt="Google+"  width="20px" height="20px"></a>
                            <a href="https://www.instagram.com/"><img src="{% static 'img/instalogo.png' %}" alt="Instagram"  width="20px" height="20px"></a>
                        </div>
                </div>
            <div class="container">
               {% block contenido %}

               {% endblock %}
            </div>
            <script src="{% static 'js/jquery-3.3.1.js' %}"></script>
        <script src="{% static 'js/bootstrap.js' %}"></script>
          
          
        </div> 
        <footer class="row firma">
            <div class="col-sm-12 text-right ">
                <p>Matias Fernández<br>
                Diego González<br>
                2018</p>
            </div>
     </footer>
    
        
</body>
</html>

templates/contacto/contacto_form.html
{%extends 'base/base.html'%}

{% block contenido %}
<form method="post">
	{% csrf_token %}
	{{ form.as_p }}
	<button type="submit">Guardar</button>
</form>
{% endblock %}

templates/contacto/contacto_list.html
{% extends 'base/base.html' %}

{% block contenido %}
<table class="table table-bordered">
    <thead>
        <tr>
            <td>#</td>
            <td>Rut</td>
            <td>Nombre</td>
            <td>Email</td>
            <td>Telefono</td>
            <td>Región</td>
            <td>Comuna</td>
        </tr>
    </thead>
    <tbody>
        {% if contactos %}
        {% for contacto in contactos %}
        <tr>
            <td>{{ contacto.id }}</td>
            <td>{{ contacto.rut }}</td>
            <td>{{ contacto.com_name }}</td>
            <td>{{ contacto.email }}</td>
            <td>{{ contacto.phone }}</td>
            <td>{{ contacto.reg }}</td>
            <td>{{ contacto.city }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <h1>No hay registro de contacto</h1>
        {% endif %}
    </tbody>
</table>
{% endblock %}

templates/mascota/index.html
{% extends 'base/base.html' %}

templates/mascota/mascota_form.html
{% extends 'base/base.html' %}

{% block contenido %}
<form method="post">
	{% csrf_token %}
	{{ form.as_p }}
	<button type="submit">Guardar</button>
	
</form>	
{% endblock %}

templates/mascota/mascota_list.html
{% extends 'base/base.html' %}

{% block contenido %}
<table class="table table-bordered">
	<thead>
		<tr>
			<td>#</td>
			<td>Nombre</td>
			<td>Raza</td>
			<td>Descripcion</td>
			<td>Estado</td>

		</tr>>

	</thead>
	<tbody>
		{% if mascotas %}
		{% for mascota in mascotas %}

		<tr>
			<td>{{ mascota.id }}</td>
			<td>{{ mascota.nombre }}</td>
			<td>{{ mascota.raza }}</td>
			<td>{{ mascota.descripcion }}</td>
			<td>{{ mascota.estado }}</td>
			

		</tr>>
		{% endfor %}
		{% else %}
		<h1> No hay registros de mascotas</h1>

		{% endif %}
	</tbody>
</table>

{% endblock %}